### PR TITLE
Updated alpine to 3.12; updated kustomize to 3.8.0

### PR DESCRIPTION
**Pull request by godlikeachilles**
Newer stuff

### CODE REVIEW

**Comment by codekoala** [comment]
Thank you for this!

**Comment by godlikeachilles** [comment]
Thanks for merging this. If ok could you pls also add extra tag (v3.8.0) to the dockerhub image? :)

**Comment by codekoala** [comment]
Done!

**Comment by godlikeachilles** [comment]
> 
> 
> Done!

Cheers!

**Pull request merged**
